# Generated by Django 5.0.6 on 2024-05-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=250, null=True, unique=True, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='app.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('brand', models.CharField(max_length=300, verbose_name='Brand')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(editable=False, max_length=300, null=True, unique=True, verbose_name='URL')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=7, verbose_name='Price')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Image')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Available Product',
                'verbose_name_plural': 'Available Products',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.product',),
        ),
    ]
